services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    command:
      - --providers.docker.exposedByDefault=false
      - --entryPoints.web.address=:80
      - --log.level=DEBUG
    ports:
      - 80:80
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    tty: true
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
      - type: bind
        source: ./prometheus_data
        target: /prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    user: ":"
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    tty: true
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - ${METRICS_DASHBOARD_PORT}:3000
    volumes:
      - type: bind
        source: ./grafana_data
        target: /var/lib/grafana
    user: ":"
    restart: always
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    tty: true
    restart: always
networks:
  default:
    name: sns-network
